[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ermc"
version = "0.3.0"
authors = [
    { name = "Edison Manrique Chocce" }
]
description = "Exact Regression Mathematical Core - Python Bindings"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU Affero General Public License v3 (AGPLv3)",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]

[project.urls]
"Homepage" = "https://github.com/edison-manrique/ermc"
"Bug Tracker" = "https://github.com/edison-manrique/ermc/issues"
